DROP TABLE IF EXISTS NodeJSTraining.Products;

CREATE TABLE NodeJSTraining.Products (
	ID INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(255) NOT NULL,
	Price DECIMAL(18,2) NOT NULL,
	Quantity int	NOT NULL,
	PRIMARY KEY (ID)
);