DROP TABLE IF EXISTS NodeJSTraining.Users;

CREATE TABLE NodeJSTraining.Users (
	ID INT NOT NULL AUTO_INCREMENT,
	FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	BirthDate DATE	NOT NULL,
	Username VARCHAR(255) NOT NULL,
	Password VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);